### ISSUE TITLE
bin/nri-nagios exits immediately on invalid command output

### ISSUE THREAD

**Issue by barrypitman** [newrelic/nri-nagios#93] opened 2024-01-16 11:00 UTC
I have ~30 checks that I want to run on certain virtual machines, and I'd like to report the output of the commands to New Relic using this integration.

However, I found that if just one of the checks outputs an invalid exit code / output, then none of the checks report back to New Relic, and the integration exits with an error:

```
root@vm /var/log # /var/db/newrelic-infra/newrelic-integrations/bin/nri-nagios  -service_checks_config /etc/newrelic-infra/integrations.d/nagios-service-checks.yml -verbose
panic: runtime error: index out of range [1] with length 0

goroutine 118 [running]:
main.parseOutput({0x0?, 0xc000117ca0?})
        /go/src/github.com/newrelic/nri-nagios/src/main.go:275 +0x245
main.collectServiceCheck({{0xc00016d140, 0x2f}, {0xc0001bb580, 0x1, 0x1}, 0xc000115560, 0x1}, 0xc0000a25a0?, 0xc0000a2540?, {0x5436d3, ...})
        /go/src/github.com/newrelic/nri-nagios/src/main.go:181 +0x58a
main.main.func1({{0xc00016d140, 0x2f}, {0xc0001bb580, 0x1, 0x1}, 0xc000115560, 0x1})
        /go/src/github.com/newrelic/nri-nagios/src/main.go:100 +0xa5
created by main.main in goroutine 1
        /go/src/github.com/newrelic/nri-nagios/src/main.go:99 +0x5a7

``` 
Of course, the cause of the failing check should be addressed, but this shouldn't cause the entire suite of checks to stop reporting, the integration should report the result of the failing check as an error, similar to what Nagios would do in this scenario.

**Comment by paologallinaharbur** [comment] 2024-01-16 14:13
The root cause seems to be `match` having fewer elements than expected due to the command output. We can add a check to exit in a more graceful way avoiding a panic

**Comment by abhishuraina** [comment] 2024-11-18 11:36
@barrypitman We have fixed the issue it won't stop the entire checks on invalid inputs. 
Here's the pre release link - https://github.com/newrelic/nri-nagios/releases/tag/v2.10.1.
After a week if there are no issues it will be released to production.

**Closed by abhishuraina** 2024-11-18 11:36 UTC
Labels: priority/backlog
